"""키오스크 UI 색상 및 폰트 설정."""

# 색상
BG = "#F5F0EB"
PANEL = "#FFFFFF"
PRIMARY = "#6F4E37"
PRIMARY_DARK = "#4A3225"
PRIMARY_DEEP = "#352218"
ACCENT = "#C8956C"
ACCENT_LIGHT = "#E8C9A8"
TEXT = "#2C1810"
TEXT_LIGHT = "#8B7355"
SUCCESS = "#2E7D32"
SUCCESS_LIGHT = "#C8E6C9"
SUCCESS_DARK = "#1B5E20"
DANGER = "#E57373"
BORDER = "#E0D5C8"

# 헤더·버튼 (흰색 글꼴 없이 진한 글씨 사용)
HEADER_BG = PANEL
HEADER_TEXT = PRIMARY_DARK
HEADER_TEXT_MUTED = TEXT_LIGHT
BTN_PRIMARY_FG = TEXT
BTN_PRIMARY_BG = ACCENT_LIGHT
BTN_PRIMARY_ACTIVE = ACCENT
BTN_ACCENT_FG = TEXT
BTN_ACCENT_BG = "#F0E4D8"
BTN_ACCENT_ACTIVE = ACCENT_LIGHT
BTN_SUCCESS_FG = SUCCESS_DARK
BTN_SUCCESS_BG = SUCCESS_LIGHT
BTN_SUCCESS_ACTIVE = "#A5D6A7"
BTN_GHOST_FG = TEXT
BTN_GHOST_BG = BG

# 폰트
FONT_TITLE = ("Apple SD Gothic Neo", 36, "bold")
FONT_HEADING = ("Apple SD Gothic Neo", 22, "bold")
FONT_BODY = ("Apple SD Gothic Neo", 16)
FONT_BUTTON = ("Apple SD Gothic Neo", 18, "bold")
FONT_PRICE = ("Apple SD Gothic Neo", 20, "bold")
FONT_SMALL = ("Apple SD Gothic Neo", 14)

# 창 크기 (키오스크 터치스크린 비율)
WINDOW_WIDTH = 1024
WINDOW_HEIGHT = 768

# 타임아웃 (초)
PROCESSING_SECONDS = 5
COMPLETE_TO_RECEIPT_SECONDS = 2
MENU_IDLE_SECONDS = 30
